export const WEBSOCKET_EVENTS = {
	CREATE_ROOM: "POKER:CREATE_ROOM",
	JOIN_ROOM: "POKER:JOIN_ROOM",
	VOTE: "POKER:VOTE",
	REVEAL: "POKER:REVEAL",
	HIDE: "POKER:HIDE",
	RESET: "POKER:RESET",
	ROOM_STATE: "POKER:ROOM_STATE",
	LEAVE: "POKER:LEAVE",
} as const;
